version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache-container
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Senha!123
      POSTGRES_DB: agenda
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  composer:
    image: composer:2
    container_name: composer-container
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install"]

networks:
  app-network:

volumes:
  pgdata:
