services:
  php-apache:
    build: .
    container_name: php-apache-container
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Senha!123
      POSTGRES_DB: agenda
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - app-network
    depends_on:
      - postgres

  composer:
    image: composer:2
    container_name: composer-container
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install"]

  frontend:
    container_name: frontend-react
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    networks:
      - app-network
    working_dir: /app
    command: bash -c "npm install && npm run dev"

networks:
  app-network:

volumes:
  pgdata:
